nelmio_api_doc:
    documentation:
        info:
            title: Users API
            description: CRUD API for users
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
